### ISSUE TITLE
List defined schema elements in imenu ?

### ISSUE THREAD

**Issue by dod38fr** [magoyette/openapi-yaml-mode#1]
Hello

Thanks for this emacs mode, it really helps me deal with an openapi file.

To help navigation in this file, would it be possible to list the schemas defined in `Components` section ?

In other words, if an api file has:
```yaml
components:
  schemas:
    foo: ...
    bar: ...
```

I'd like imenu to show something like:
```
*Elements* /  schemas / foo
*Elements* /  schemas / bar
```

Would it be possible ?

All the best

Dod
